services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx:inception
    env_file: .env
    ports:
      - "${NGINX_PORT}:443"
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: on-failure

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mariadb:inception
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${WP_DB_NAME}
      - MYSQL_USER=${WP_DB_USER}
      - MYSQL_PASSWORD=${WP_DB_PASS}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception
    restart: on-failure
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "${WP_DB_USER}", "-p${WP_DB_PASS}"]
      interval: 5s
      timeout: 3s
      retries: 30

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress:inception
    env_file: .env
    environment:
      - DB_HOST=${DB_HOST}
      - WP_DB_NAME=${WP_DB_NAME}
      - WP_DB_USER=${WP_DB_USER}
      - WP_DB_PASS=${WP_DB_PASS}
      - DOMAIN=${DOMAIN}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASS=${WP_ADMIN_PASS}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PASS=${WP_USER_PASS}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_USER_DISPLAY=${WP_USER_DISPLAY}
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception
    restart: on-failure

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/mariadb-data

  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/wordpress-data

